version: '3.8'
services:
  postgres:
    container_name: postgres-internet_provider
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: "internet_provider"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: internet_provider_client
    ports: 
     - '3000:3000'
    volumes:
      - /src
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres-data:
  minio_data:
